export default {
  index: 'Demo dự án',
  setup_project: 'Setup dự án',
  connect_wallet: 'Triển khai Connect Wallet',
  build_header: 'Xây dựng Header',
  display_info: 'Xây dựng nơi hiển thị thông tin',
  fetch_smart_contract_data: 'Lấy dữ liệu trên Smart Contract',
  build_donation_form: 'Xây dựng Donation Form',
  call_write_function: 'Gọi Write Function rrong Smart Contract',
  refactor_code_base: 'Refactor Code Base',
  build_loader: 'Xây dựng Loader',
  fetch_contract_events: 'Lấy History Events trong Contract',
  display_latest_donation: 'Hiển thị Latest Donation',
  practice_advice: 'Lời khuyên luyện tập',
  custom_provider: 'Custom Provider',
};
