export default {
  index: 'Demo',
  setup: 'Setup dự án',
  payable_and_msgvalue: 'Payable & `msg.value`',
  wei: 'Wei',
  validations_with_require: 'Validations với `require()`',
  constant_variable: 'Biến Constant',
  immutable_variable: 'Biến Immutable & `constructor()`',
  validations_with_if_else: 'Validations với `if/else` & `revert()`',
  sending_ether: 'Gửi Ether thông qua một Function',
  fallback_receive_functions: 'Fallback & Receive Functions',
  this_keyword: '`this` keyword',
  error: 'Custom Error',
  modifier: 'Modifier',
  chainlink_introduce: 'Giới thiệu Chainlink Oracle',
  setup_chainlink_data_feed: 'Setup Chainlink Data Feed',
  convert_value_to_wei: 'Chuyển giá trị thành Wei',
  ai_coding_agent: 'Sử dụng AI',
  library: 'Library',
  mapping_and_array_funders: 'Mapping & Array Funders',
  event: 'Event',
};
